version: "3.9"

services:
  dart-server:
    build: .
    container_name: my_server
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - mongodb+srv://<admin>:<CLzyys6WZqXHvI1J>@cluster0.1misyhm.mongodb.net/?appName=Cluster0
